DROP DATABASE IF EXISTS tpjo;

CREATE DATABASE tpjo;

CREATE TABLE tpjo.sport(
    id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    picto VARCHAR(50) NOT NULL
);

CREATE TABLE tpjo.epreuves(
    id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    sport_id TINYINT UNSIGNED,
    FOREIGN KEY(sport_id) REFERENCES sport(id)
);